apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  labels:
    app: first-app
  annotations:
    author: Dmitry_Sakhno
spec:
  replicas: 5
  strategy: #определяет стратегию развертывания
    type: RollingUpdate #тип стратегии
    rollingUpdate: #определяет стратегию обновления
      maxSurge: 1 #максимальное кол-во модулей созданных сверх желаемого кол-ва реплик во время обновления, default 25%
      maxUnavailable: 0 #максимальное кол-во модулей недоступных во время обновления, default 25%
  selector:
    matchLabels:
      project: testMatchLabels
  template:
    metadata:
      labels:
        project: testMatchLabels
    spec:
      containers:
        - name: jule10
          image: amizory/k8s-practice:v1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
