apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: Dmitry_Sakhno
spec:
  serviceAccountName: amizory #definitive user
  nodeSelector:
    test: Hello
  #POD LEVEL
  #securityContext:                  #CONTAINER LEVEL
  #runAsUser: 1000
  #runAsNonRoot: false
  #allowPrivilegeEscalation: false
  containers:
    - name: test
      image: amizory/k8s-practice:latest
      securityContext: #CONTAINER LEVEL
        runAsUser: 1000 #run without root access
        runAsNonRoot: true #cancel if app use root permission
        readOnlyRootFilesystem: true #overwriting the file system
        allowPrivilegeEscalation: false #off privilege enhancement
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 81
