apiVersion: v1
kind: LimitRange
metadata:
  name: <TEXT>
spec:
  limits:
    - type: Container
      default:
        cpu: "500m"
        memory: "256Mi"
      defaultRequest:
        cpu: "200m"
        memory: "128Mi"
