apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storageclass
provisioner: kubernetes.io/no-provisioner
parameters:
  type: local
  fsType: ext4
  reclaimPolicy: Retain
  volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  local:
    path: /mnt/data
  storageClassName: local-storageclass
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storageclass
