apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: {{ .Values.ports.containerPort }}
