apiVersion: v1
kind: ReplicationController
metadata:
  name: test-replication-controller
spec:
  replicas: 5
  selector:
    app: test-replication
  template:
    metadata:
      name: test-replication-app
      labels:
        app: test-replication
    spec:
      containers:
        - name: test-replication-image
          image: amizory/k8s-practice:latest
          ports:
            - containerPort: 82
